---
title: "431 Project B Instructions for Fall 2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

# What is on this Website

- **Study 1** Instructions (be sure to look at all Study 1 tabs in the top menu)
- **Study 2** Instructions (be sure to look at all Study 2 tabs in the top menu)
- A [Checklist](tasks.html) of the tasks that need to be accomplished for Project B.
- The top menu also provides links to contact us, and to the 431 home page.

## Project B Deliverables

You will complete two Google Forms in November...

- The Class Survey (used for Study 1 data): [details here](survey1.html), due 2020-11-11 at 11 PM.
- The Study 2 Data Plan: [details here](your5.html), due Thursday 2020-11-19 at Noon. This form also gives you the opportunity to tell me whether you are working with a partner.

The bulk of the work, though, is due on 2020-12-10 at noon.

- You will complete two studies, building a report using R Markdown for each, and those reports will be due on 2020-12-10 at noon.
- On 2020-12-01, Dr. Love will pose a series of questions about your two Studies, and you will respond to those questions through a short **oral presentation**.
    1. A substantial majority of the project groups will prepare a pre-recorded video presentation to respond to Dr. Love's questions, and that, too, will be due on 2020-12-10 at noon.
    2. A few (12-15) of the project groups will instead meet through Zoom with Dr. Love to have a 15-20 minute conversation about their Project B on either 2020-12-09, 2020-12-10, or 2020-12-11.
- You will also complete a **Google Form Self-Evaluation**, as you did in Project A, also due 2020-12-10 at Noon. This, too, will be available on 2020-12-01.

#### Partnerships?

You can work alone, or with one other person on this project. If you work as a pair, you will commit to that in the [Study 2 Data Plan form](your5.html). Each of you will receive the team grade for the project reports, and an individual grade for the other components of the project.

# Study 1

- Study 1 is about making descriptive and exploratory comparisons and summaries of data. It's not (really) about building sophisticated statistical models.
- Study 1 involves taking a Class Survey of 65 items. The same survey was also taken by 67 students and TAs involved with 431 in Fall 2019.
    - You will take the survey by 2020-11-11 at 11 PM, and you'll find it at http://bit.ly/431-projectB-survey.
- After all students this year complete the survey, Dr. Love will then create data describing the results from 2019 and 2020 and share them with you. 
- Every project group will thus start Study 1 with the same original data set of survey results, but you will each look at different survey items and identify different analytic questions.
- You will ingest, merge and clean the data in R, then select variables to complete any four out of a set of six potential analyses, described in these instructions. 
    - You can do all six analyses if you like (as preparation for Quiz 2, for instance) but you will only present four in your report.
    - All of the material you need (from a statistical perspective) to do these analyses was covered in Classes 1-20.
- The **Study 1: Class Survey** [section](survey1.html) of this website includes complete Study 1 instructions.
    - This includes a [Study 1 Demonstration Project](survey6.html) (posted 2020-11-09) that should help you build your report.

# Study 2

- Study 2 is about building a model and making predictions. You will complete all elements of a data science project designed to create a statistical model for a quantitative outcome, then use it for prediction, and assess the quality of those predictions.
- Study 2 involves working with data either from NHANES or from a source you develop.
    - Dr. Love will provide detailed instructions regarding using NHANES data.
    - If you want to use other data, you'll have to get Dr. Love's permission by filling out a form. Detailed specifications of what standards your data will have to meet will be provided.
- Every project group will be working with different data sets in Study 2, as a result.
- Study 2 involves the prediction of a quantitative outcome using a key predictor and some additional predictors in two linear regression models, and then comparing those two models using tools we've already seen, plus some tools we will develop in classes 22-24, so that you'll have all relevant material covered before the Thanksgiving Break.
- The Study 2: Your Data section of this website includes complete Study 2 instructions.
    - Study 2 Demonstration materials that may help you build your report will appear before the Thanksgiving break. 

# Grading

Project B will be graded by Dr. Love on a scale from 0-100.

- The combined study report (Study 1 and Study 2) is worth 50 points.
- The oral presentation in reaction to the questions Dr. Love will pose on 2020-12-01 is worth 40 points.
- The self-evaluation is worth 10 points.
- Late work on Project B will be severely penalized.

You should know now that Dr. Love will provide extremely limited feedback on your Project B work - not much more than a grade, really, assuming you've done a generally creditable job. The timeline is simply too tight on my end, and this has been a tough year from which I need to recover in late December. I apologize in advance.

# Questions?

If you have questions, let us know about them on Piazza using the projectB folder, or speak with Dr. Love before or after class, or discuss them with the TAs during office hours.

This page was last updated: `r Sys.time()`.
