---
title: "Step 1. Taking the Class Survey"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

Visit http://bit.ly/431-projectB-survey to take the survey. This will take you to a Google Form, and you'll need to be logged into Google via CWRU to take the survey.

- **Deadline** Please [complete the survey](http://bit.ly/431-projectB-survey) by 11 PM on Wednesday 2020-11-11.
- **Note** The survey is now complete, for 2020. [Go here](survey3.html) to obtain the data.

## No longer relevant information

There are [65 items, as listed here](survey2.html), so this will take a little while to complete, but remember that your fellow students need data. While none of the items (except your name, at the bottom of this page) are marked as required so that you can skip around if you like, we really hope you will answer all 65 items.

So as to reduce your burden, the completion of this survey will also serve as the Minute Paper after Class 21.

Dr. Love will have the ability to associate your responses with your email address and name, but he will delete this information once he verifies that everyone has completed the task. The data will be thoroughly de-identified before [they are made available to you](survey3.html).


This page was last updated: `r Sys.time()`.
