---
title: "Study 2 Demonstration Materials"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

**Posted 2020-11-17**: Links are now available for all Study 2 demonstration materials.

Remember that a general outline and set of instructions for the Study 2 report [is available here](your6.html).

## The Study 2 Demonstration Project

In the demo, I demonstrate many (but not all) of the elements you would need to complete in Study 2, including:

- data ingest
- cleaning the data, as well as
- building a codebook for the final variables and describing them numerically, plus
- partitioning the data
- considering (and applying) a transformation
- fitting and summarizing a big model and a small model
- comparing the two models within the training sample
- validating and comparing the two models within the holdout (test) sample

for a simulated data set containing information on 999 subjects about high blood pressure control.

## The Files

- The R Markdown file [can be downloaded here](https://github.com/THOMASELOVE/431-2020/blob/master/projects/projectB/431-projectB-study2-demo.Rmd).
- The HTML result [can be viewed here](https://rpubs.com/TELOVE/projB-study2-demo), and [can be downloaded here](https://github.com/THOMASELOVE/431-2020/blob/master/projects/projectB/431-projectB-study2-demo.html).

The data file for the Study 2 Demonstration Project is described in the R Markdown and HTML files above and is found on [the 431-data website](https://github.com/THOMASELOVE/431-data). It is called:

- **hbp_study.csv** (999 observations in 12 columns)

The subjects are identified with a code called `subj_id` 
 
## Caveats

1. The demonstration project does not precisely follow the requirements from Study 2 for certain sections, because that is a big part of your job. In particular, I'll note that I augmented the instructions in the [Report Specifications](your6.html) for Sections 3 (Cleaning the Data) and 5 (Your Final Variables) after the demonstration project was created, so I placed a short note at the start of those sections to remind you to look at the detailed instructions

2. In the demonstration project, I don't make much of an effort to make attractive graphs.

3. Outside of those caveats, these demonstrations are meant to be accurate and reflect the level of detail I'm looking for, although it is certainly possible to expand on these demonstrations in your work, if that seems helpful. I believe the demonstration project documents to be largely accurate, but many eyes will find some issues, eventually. 

If people find corrections and would be good enough to post them to Piazza (under the corrections and projectB folders, please) I will attempt to reflect those edits in revisions. If I do something in the demonstration project that appears to be in conflict with the instructions for Study 2, then (a) please let me know, and (b) treat the Study 2 instructions as your guidepost in completing your work.

## Video to help with cleaning NHANES data

- On 2020-11-17, Dr. Love built a video called **video_nhanes_example.mp4** available on our shared Google Drive in the Project B folder.
    - In the video, Dr. Love downloads data using `nhanesA` from three data sets in NHANES 2017-18, selects a few variables, merges the files, and then cleans up one of the variables to turn "Don't Know" and "Refused" responses to missing values.
    - Dr. Love made a mistake at the very end of the video when he suggested you ask questions via Canvas. Of course, he meant via [Piazza](https://piazza.com/case/fall2020/pqhs431).
- The [R Markdown file](https://github.com/THOMASELOVE/431-2020/blob/master/projects/projectB/video_nhanes.Rmd) Dr. Love displayed and ran in the video is also available.


This page was last updated: `r Sys.time()`.


