---
title: "Study 2 Data Plan"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

Visit http://bit.ly/431-projectB-data-plan to complete a form describing your data plan for Study 2. You'll need to be logged into Google via CWRU to see and complete the form. If you are working with a partner, you each need to submit the Data Plan, and please submit the same responses to the questions about the data you're using.

- **Deadline** Please [complete the data plan](http://bit.ly/431-projectB-data-plan) as soon as possible, but definitely by Noon on Thursday 2020-11-19.

The data plan form asks the following questions:

1. Will you be working on Project B with a partner? (and if so, who is your partner?)
2. Will you be using NHANES data for Project B Study 2? (Yes/No)

- if you will be using NHANES data, you will then skip to question 5.
- if you will not be using NHANES data, you will also answer questions 3 and 4.

3. What data set will you be using for Project B Study 2?
4. Provide a URL which you have used to obtain the data, and which Dr. Love can also use to obtain the data.

5. Who are the subjects in the data set (are they people, animals, and how were they selected to participate)?
6. What outcome do you plan to use? (Please provide enough information so that Dr. Love understands your outcome and can verify that it is quantitative in nature, rather than categorical.)
7. What is the key predictor of your outcome that you plan to use? (Please provide enough information so that Dr. Love understands your key predictor and also specify whether it is quantitative or categorical in nature, and if it is categorical, tell me what the categories are.)
8. What are the other 3-8 predictor variables you plan to use in your study? (Specify each of your 3-8 variables, and for each, describe the variable's meaning if it's not clear, and tell me whether it is categorical or quantitative. If it's categorical, tell me what the categories are.)
9. How many subjects in your data have complete information on all variables you plan to study? (must be between 250 and 10,000)

That's it. Dr. Love will review your results and get back to you to tell you whether your proposed approach is approved or not. If not, you'll have to edit your submission and resubmit the form.


This page was last updated: `r Sys.time()`.
